version: 2
jobs:
  build:
    working_directory: ~/westegg
    docker:
      - image: circleci/node:10.15
        environment:
          SHARP_DIST_BASE_URL: https://s3-us-west-2.amazonaws.com/sharp-distro/
    steps:
      - checkout
      - run:
          name: Updating...
          command: node common/scripts/install-run-rush.js update --full
      - run:
          name: Checking for inconsistent dependency versions
          command: node common/scripts/install-run-rush.js check
      - run:
          name: Installing...
          command: node common/scripts/install-run-rush.js install
      - run:
          name: Building...
          command: node common/scripts/install-run-rush.js rebuild --verbose -p 1
