version: 2
jobs:
  build:
    working_directory: ~/westegg
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Installing Sharp with --build-from-source because direct download 403s
          command: SHARP_DIST_BASE_URL=https://s3.amazonaws.com/MYS3NAME/ npm install
      - run:
          name: Updating...
          command: node common/scripts/install-run-rush.js update --full
      - run:
          name: Checking for inconsistent dependency versions
          command: node common/scripts/install-run-rush.js check
      - run:
          name: Installing...
          command: node common/scripts/install-run-rush.js install
      - run:
          name: Building...
          command: node common/scripts/install-run-rush.js rebuild --verbose -p 1
